# Generated by Django 3.2.12 on 2022-02-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glavnaya', '0003_post_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
